language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  chrome: stable
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
before_script:
  - npm install -g @angular/cli
  - npm install -g codecov
script:
#  - ng lint
  - npm run test-ci
  - codecov
  - ng build angular-editor
